---
- name: Setup Fonts
  hosts: localhost
  become: true
  connection: local
  gather_facts: false
  vars:

  tasks:
    - name: Install coding fonts (pacman)
      ansible.builtin.package:
        name:
          - ttf-firacode-nerd
          - otf-monaspace-nerd
          - ttf-inconsolata-nerd
          - ttf-cascadia-code-nerd
          - ttf-space-mono-nerd
          - ttf-roboto-mono-nerd
        state: present

    # - name: Install coding fonts (AUR)
    #   kewlfft.aur.aur:
    #     use: yay
    #     name:
    #     state: present
    #   become: true
    #   become_user: aur_builder

    # - name: Install presentation fonts (pacman)
    #   ansible.builtin.package:
    #     name:

    #     state: present

    - name: Install coding fonts (AUR)
      kewlfft.aur.aur:
        use: yay
        name:
          - ttf-raleway-variable
          - ttf-roboto-variable
          - ttf-inter
        state: present
      become: true
      become_user: aur_builder