return {
	{ "ficcdaf/ashen.nvim" },
	{ "catppuccin/nvim", name = "catppuccin" },
	{ "zootedb0t/citruszest.nvim" },
	{ "scottmckendry/cyberdream.nvim", opts = { borderless_telescope = true } },
	{ "embark-theme/vim" },
	{ "neanias/everforest-nvim" },
	{ "rebelot/kanagawa.nvim" },
	{ "ramojus/mellifluous.nvim" },
	{ "bluz71/vim-moonfly-colors", name = "moonfly" },
	{ "EdenEast/nightfox.nvim", opts = { options = { dim_inactive = true } } },
	{ "ricardoraposo/nightwolf.nvim" },
	{ "AlexvZyl/nordic.nvim" },
	{ "dgox16/oldworld.nvim" },
	{ "navarasu/onedark.nvim", opts = { style = "cool" } },
	{ "MarcoKorinth/onehalf.nvim" },
	{ "rmehri01/onenord.nvim" },
	{ "rose-pine/neovim", name = "rose-pine" },
	{ "folke/tokyonight.nvim" },
	{ "sam4llis/nvim-tundra", opts = { dim_inactive_windows = { enabled = true } } },
	{ "vague2k/vague.nvim" },
	{ "zenbones-theme/zenbones.nvim", dependencies = "rktjmp/lush.nvim" },
}
