---
- name: Machine setup
  hosts: localhost
  become: true
  connection: local
  gather_facts: true
  vars:

  tasks:
    - name: Get my user
      ansible.builtin.set_fact:
        remote_regular_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"
    
    - name: Check user
      ansible.builtin.debug:
        var: remote_regular_user

    - name: Create the `aur_builder` user
      become: yes
      ansible.builtin.user:
        name: aur_builder
        create_home: yes
        group: wheel

    - name: Allow the `aur_builder` user to run `sudo pacman` without a password
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        mode: 0644
        validate: 'visudo -cf %s'

    - name: Install packages
      ansible.builtin.package:
        name:
          - zsh
          - git
          - htop
          - ripgrep
          - fzf
          - tmux
          - make
          - patch
          - bzip2
          - fd
          - github-cli
          - docker
          - kitty
          - exa
          - zoxide
          - jdk17-openjdk
          - ranger
          - gnome-font-viewer
          - neovim
          - firefox
        state: present

    - name: Install yay AUR helper
      kewlfft.aur.aur:
        name: yay
        use: makepkg
        state: present
      become: yes
      become_user: aur_builder

    - name: Install AUR packages
      kewlfft.aur.aur:
        name:
          - slack-desktop
          - asdf-vm
          - xdg-ninja
          - bartib
          - nb
          - spotify
        use: yay
        state: present
      become: yes
      become_user: aur_builder

    - name: Change shell to zsh
      ansible.builtin.user:
        name: "{{ remote_regular_user }}"
        groups: docker
        append: yes
        shell: /usr/bin/zsh

- name: Setup Docker
  ansible.builtin.import_playbook: ./playbooks/docker.yml
  vars: 
    remote_regular_user: "{{ remote_regular_user }}"

- name: Setup Android SDK
  ansible.builtin.import_playbook: ./playbooks/android-sdk.yml
  vars: 
    remote_regular_user: "{{ remote_regular_user }}"

- name: Setup Fonts
  ansible.builtin.import_playbook: ./playbooks/fonts.yml
  vars: 
    remote_regular_user: "{{ remote_regular_user }}"

- name: Cleanup
  hosts: localhost
  become: true
  connection: local
  gather_facts: false
  tasks:
    - name: Remove `aur_builder` user
      ansible.builtin.user:
        name: aur_builder
        state: absent
        remove: yes
        
    - name: Cleanup `aur_builder` sudo permissions
      ansible.builtin.file:
        path: /etc/sudoers.d/11-install-aur_builder
        state: absent